/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.project;

/**
 *
 * @author 1-CTaylor
 */
public class jframehome extends javax.swing.JFrame {

    boolean setVisible;

    /**
     * Creates new form jframehome
     */
    public jframehome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundwhiteHM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttnLogOut = new javax.swing.JButton();
        panelHM = new javax.swing.JPanel();
        bttnHome = new javax.swing.JButton();
        bttnMembers = new javax.swing.JButton();
        bttnBooks = new javax.swing.JButton();
        bttnOverdue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        backgroundwhiteHM.setBackground(new java.awt.Color(255, 255, 255));
        backgroundwhiteHM.setPreferredSize(new java.awt.Dimension(712, 464));

        bttnLogOut.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bttnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        bttnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/logout.PNG"))); // NOI18N
        bttnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLogOutActionPerformed(evt);
            }
        });

        panelHM.setBackground(new java.awt.Color(238, 238, 238));
        panelHM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 58, 58), 5));

        javax.swing.GroupLayout panelHMLayout = new javax.swing.GroupLayout(panelHM);
        panelHM.setLayout(panelHMLayout);
        panelHMLayout.setHorizontalGroup(
            panelHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        panelHMLayout.setVerticalGroup(
            panelHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        bttnHome.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bttnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/tabhome.png"))); // NOI18N
        bttnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnHomeActionPerformed(evt);
            }
        });

        bttnMembers.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bttnMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/tabmembers.png"))); // NOI18N

        bttnBooks.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bttnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/tabbooks.png"))); // NOI18N

        bttnOverdue.setBackground(new java.awt.Color(222, 215, 200));
        bttnOverdue.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bttnOverdue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/taboverdue.png"))); // NOI18N
        bttnOverdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnOverdueActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/logousethisone.png"))); // NOI18N

        javax.swing.GroupLayout backgroundwhiteHMLayout = new javax.swing.GroupLayout(backgroundwhiteHM);
        backgroundwhiteHM.setLayout(backgroundwhiteHMLayout);
        backgroundwhiteHMLayout.setHorizontalGroup(
            backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(859, Short.MAX_VALUE))
            .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundwhiteHMLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(bttnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)))
                    .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                            .addComponent(bttnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(bttnMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addComponent(bttnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bttnOverdue, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelHM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        backgroundwhiteHMLayout.setVerticalGroup(
            backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundwhiteHMLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addGap(0, 393, Short.MAX_VALUE))
            .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                            .addComponent(bttnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(backgroundwhiteHMLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bttnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(backgroundwhiteHMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttnMembers)
                                    .addComponent(bttnOverdue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panelHM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(2, 2, 2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundwhiteHM, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundwhiteHM, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnLogOutActionPerformed

    private void bttnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnHomeActionPerformed

    private void bttnOverdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnOverdueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnOverdueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframehome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframehome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframehome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframehome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframehome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundwhiteHM;
    private javax.swing.JButton bttnBooks;
    private javax.swing.JButton bttnHome;
    private javax.swing.JButton bttnLogOut;
    private javax.swing.JButton bttnMembers;
    private javax.swing.JButton bttnOverdue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelHM;
    // End of variables declaration//GEN-END:variables
}
